In [1]:
import numpy as np

In [2]:
oneDarray = np.array([1,2,3])
print(oneDarray) # similar to list

[1 2 3]


In [3]:
twoDarray = np.array([[1,2,3],[4,5,6]])
print(twoDarray) # similar to table with rows and columns

[[1 2 3]
 [4 5 6]]


In [4]:
print(twoDarray[1,2])

6


In [5]:
threeDarray = np.array([[[1,2,3],[-1,-2,-3]],[[4,5,6],[-4,-5,-6]]])
print(threeDarray) # 2 Two-Dimension Arrays gives me one Three-Dimension Array. 

[[[ 1  2  3]
  [-1 -2 -3]]

 [[ 4  5  6]
  [-4 -5 -6]]]


In [6]:
print(threeDarray[0])

[[ 1  2  3]
 [-1 -2 -3]]


In [7]:
print(threeDarray[0,1])

[-1 -2 -3]


In [8]:
print(threeDarray[0,1,0])

-1


In [9]:
shape = np.shape(twoDarray) # returns a tuple
print(shape) # 2 Dimension array and 3 indexes

(2, 3)


In [58]:
# looping through two dimension numpy arrays

twoDarray = np.array([[1,2,3],[4,5,6]])
for i in twoDarray:
    for j in i:
        print(j)

1
2
3
4
5
6


In [60]:
# looping through three dimension numpy arrays

threeDarray = np.array([[[1,2,3],[-1,-2,-3]], [[4,5,6],[-4,-5,-6]]])
for i in threeDarray:
    for j in i:
        print(j)


[1 2 3]
[-1 -2 -3]
[4 5 6]
[-4 -5 -6]


In [12]:
for i in threeDarray:
    for j in i:
        for k in j:
            print(k)

1
2
3
-1
-2
-3
4
5
6
-4
-5
-6


In [13]:
zerosArray = np.zeros(10)
print(zerosArray)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [14]:
zerosArray = zerosArray.astype(int)
print(zerosArray)

[0 0 0 0 0 0 0 0 0 0]


In [15]:
onesArray = np.ones(10) # ones array converted to integer.
OnesArray = onesArray.astype(int)
print(OnesArray)

[1 1 1 1 1 1 1 1 1 1]


In [16]:
matrix = np.array([[1,2,3],[4,5,6]]) # 2-D Numpy array. 
newmatrix = (matrix + 2) # add 2 to each element of arrays. 
print (newmatrix)

[[3 4 5]
 [6 7 8]]


In [17]:
matrix = np.array([[1,2,3],[4,5,6]]) # 2-D Numpy array. 
newmatrix = (matrix - 2) # subtract 2 to each element of arrays. 
print (newmatrix)

[[-1  0  1]
 [ 2  3  4]]


In [18]:
tbl = np.array([[2,6,4], [1,8,3]])         # 2-D Numpy array. 
new_tbl = tbl * 2         # multiply 2 to each element in both arrays. 
print(new_tbl)

[[ 4 12  8]
 [ 2 16  6]]


In [19]:
data = np.array([[1,13,1], [6,7,3]])
operated_data = data / 2           # "/" is float division and "//" is integer division
print(operated_data)

[[0.5 6.5 0.5]
 [3.  3.5 1.5]]


In [20]:
data = np.array([[1,3,1], [6,7,4]])
operated_data = data ** 2           # squaring the elements in arrays.
print(operated_data)

[[ 1  9  1]
 [36 49 16]]


In [61]:
# Transposing means pairing of 0th element of 0th array with 0th element of the 1st array. 

data = np.array([[21,54,13], [90,53,82]])
print(data.T)

# 21 paired with 90, 
# 54 paired with 53, und so weiter. 

[[21 90]
 [54 53]
 [13 82]]


In [22]:
matrix1 = np.array([3,9,5])
matrix2 = np.array([0,1,3])
new_matrix = matrix1 + matrix2
print(new_matrix)           # Element-wise addition  

[ 3 10  8]


In [23]:
matrix1 = np.array([3,9,5])
matrix2 = np.array([0,1,3])
new_matrix = matrix1 - matrix2
print(new_matrix)           # Element-wise subtraction

[3 8 2]


In [24]:
matrix1 = np.array([3,9,5])
matrix2 = np.array([8,2,3])
new_matrix = matrix1 * matrix2
print(new_matrix)           # Element-wise multiplicaion  

[24 18 15]


In [25]:
matrix1 = np.array([24,50,15])
matrix2 = np.array([8,2,3])
new_matrix = matrix1 // matrix2      # integer division 
print(new_matrix)           # Element-wise division  

[ 3 25  5]


In [66]:
mat1 = np.array([[2,5,0],[5,1,9],[4,1,7]])
print(mat1)
mat2 = np.array([[8,2,3],[1,8,7],[1,3,8]])    
print(mat2)                                   
np.matmul(mat1, mat2) # multiplication of rows of 0th 2-D array with columns of 1st 2-D array. 

[[2 5 0]
 [5 1 9]
 [4 1 7]]
[[8 2 3]
 [1 8 7]
 [1 3 8]]


array([[21, 44, 41],
       [50, 45, 94],
       [40, 37, 75]])

In [45]:
# Statistics in Numpy

stats1 = np.array([[24,892,18], [12,439,174]])
print(np.min(stats1))            # minimum value in arrays

12


In [48]:
print(np.max(stats1))            # maximum value in arrays

892


In [49]:
print(np.average(stats1))         # average value 

259.8333333333333


In [50]:
print(np.median(stats1))         # median 

99.0


In [54]:
print(np.sum(stats1))            # sum of all elements in array

1559


In [56]:
print(np.std(stats1))           # standart deviation

320.0585449917284
