In [44]:
import numpy as np 


In [32]:
oneDarray = np.array([1,2,3])
print(oneDarray) # similar to list

[1 2 3]


In [33]:
twoDarray = np.array([[1,2,3],[4,5,6]])
print(twoDarray) # similar to table with rows and columns

[[1 2 3]
 [4 5 6]]


In [34]:
print(twoDarray[1,2])

6


In [35]:
threeDarray = np.array([[[1,2,3],[-1,-2,-3]], [[4,5,6],[-4,-5,-6]]])
print(threeDarray) # 2 Two-Dimension Arrays gives me one Three-Dimension Array. 


[[[ 1  2  3]
  [-1 -2 -3]]

 [[ 4  5  6]
  [-4 -5 -6]]]


In [37]:
print(threeDarray[0])

[[ 1  2  3]
 [-1 -2 -3]]


In [38]:
print(threeDarray[0,1])

[-1 -2 -3]


In [39]:
print(threeDarray[0,1,0])

-1


In [45]:
shape = np.shape(twoDarray) # returns a tuple
print(shape) # 2 Dimension array and 3 indexes

(2, 3)


In [52]:
# looping through two dimension numpy arrays

twoDarray = np.array([[1,2,3],[4,5,6]])
for i in twoDarray:
    for j in i:
        print(j)

1
2
3
4
5
6


In [62]:
# looping through three dimension numpy arrays

threeDarray = np.array([[[1,2,3],[-1,-2,-3]], [[4,5,6],[-4,-5,-6]]])
for i in threeDarray:
    for j in i:
        print(j)


[1 2 3]
[-1 -2 -3]
[4 5 6]
[-4 -5 -6]


In [67]:
for i in threeDarray:
    for j in i:
        for k in j:
            print(k)

1
2
3
-1
-2
-3
4
5
6
-4
-5
-6
